Update merged_main.yml

diff --git a/.github/workflows/merged_main.yml b/.github/workflows/merged_main.yml
--- a/.github/workflows/merged_main.yml
+++ b/.github/workflows/merged_main.yml
@@ -20,7 +20,7 @@ jobs:
     outputs:
       environment: ${{ steps.set-env.outputs.environment }}
     steps:
-      - name: Extract environment from tag
+      - name: Validate Tag Naming and Branch
         id: set-env
         run: |
           echo "GITHUB_REF: $GITHUB_REF"
@@ -28,9 +28,57 @@ jobs:
           echo "environment=$ENVIRONMENT"
           echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
 
+          # Get the tag name from the event
+          TAG_NAME=${GITHUB_REF##*/}
+ 
+          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.DS_READ_ONLY }}" "https://api.github.com/repos/Rahil-Sphinx/sampletf/releases/tags/${TAG_NAME}")
+          BRANCH_NAME=$(echo $RESPONSE | jq -r '.target_commitish')
+ 
+          # Debugging output
+          echo "GITHUB_REF: $GITHUB_REF"
+          echo "TAG_NAME: $TAG_NAME"
+          echo "RESPONSE: $RESPONSE"
+          echo "BRANCH_NAME: $BRANCH_NAME"
+          echo "ENVIRONMENT: $ENVIRONMENT"
+
+          # Check if the workflow was triggered by a tag
+          if [[ "$GITHUB_REF" != refs/tags/* ]]; then
+            echo "Workflow only triggers on tags, not on branches.";
+            exit 1; # Exit
+          fi
+          # Check for dev* tag
+          if [[ "$TAG_NAME" =~ ^dev.* ]]; then
+            # Allow dev tags on any branch except main
+            if [[ "$BRANCH_NAME" == "develop" ]]; then
+              echo "Validation passed for 'dev*' tag on the 'develop' branch."; 
+              exit 0; # Validation passed
+            else
+              echo "Validation failed: Tag name '$TAG_NAME' starts with 'dev', but the branch is not 'develop'.";
+              exit 1; # Validation failed
+            fi
+          # Check for prod* tag
+          elif [[ "$TAG_NAME" =~ ^prod.* ]]; then
+            # Allow prod tags only on main branch
+            if [[ "$BRANCH_NAME" == "main" ]]; then
+              echo "Validation passed for 'prod*' tag on the 'main' branch.";
+              exit 0; # Validation passed
+            else
+              echo "Validation failed: Tag name '$TAG_NAME' starts with 'prod', but the branch is not 'main'.";
+              exit 1; # Validation failed
+            fi
+          else
+            # Reject any tag that doesn't start with dev* or prod*
+            echo "Validation failed: Tag '$TAG_NAME' does not follow the required naming convention (dev* or prod*).";
+            exit 1; # Validation failed
+          fi
+
   owasp-scan:
-    runs-on: self-hosted    
-    steps:      
+    runs-on: ubuntu-latest    
+    needs: set-environment
+    steps:
+      - name: Print Environment
+        run: |
+          echo "Current Environment is: ${{ needs.set-environment.outputs.environment}}"
       - name: Change ownership of directory
         run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/arrk-ds
       - name: checkout the code repo
@@ -84,6 +132,9 @@ jobs:
     runs-on: self-hosted
     needs: owasp-scan
     steps:
+      - name: Print Environment
+        run: |
+          echo "Current Environment is: ${{ needs.set-environment.outputs.environment}}"
       - name: Build frontend docker image
         run: |
           cd FrontEnd
@@ -100,7 +151,7 @@ jobs:
     steps:
       - name: Print Environment
         run: |
-          echo "Environment: ${{ needs.set-environment.outputs.environment}}"
+          echo "Current Environment is: ${{ needs.set-environment.outputs.environment}}"
       - name: Setup AWS ECR Details
         uses: aws-actions/configure-aws-credentials@v4
         with:
